### ISSUE TITLE
CMS Builder Fields

### ISSUE THREAD

**Issue by bagrinsergiu** [bagrinsergiu/brizy-ui#122]
- [x] Text: https://jmp.sh/LUghdLF
- [x] Textarea: https://jmp.sh/f1nL2OF
- [x] Number: https://jmp.sh/Ufp0syU
- [x] Email: https://jmp.sh/0NZOTHx
- [x] Link: https://jmp.sh/0NZOTHx
- [x] Image: https://jmp.sh/HFq9EcX
- [x] Multi Image: https://jmp.sh/WKIBADr
- [x] File: https://jmp.sh/fnGOPiw
- [x] Select: https://jmp.sh/4VrLDs2
- [x] Reference: https://jmp.sh/w1RkywB
- [x] Multi Reference: https://jmp.sh/Yl9jm9L
- [x] Video: https://jmp.sh/9fijx1t
- [x] Color Picker: https://jmp.sh/P7CQH7c
- [x] True/ False ( switch ) - https://jmp.sh/ut13P1A
- [x] Date Picker: https://jmp.sh/ihupFLJ

---

- [ ] Checkbox - ???
- [ ] Radio Button - ???
- [ ] Button Group - ???
- [ ] Wysiwyg Editor - ???
- [ ] Post Object - ???
- [ ] Page Link - ???
- [ ] Date Time Picker: ???
- [ ] Time Picker - ???

**Comment by BogdanGCondurache** [comment]
Done!
https://projects.invisionapp.com/d/main?origin=v7#/console/17132809/401533459/preview
