### ISSUE TITLE
Edit asset title

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#168]
![Screen Shot 2020-05-12 at 2 10 08 AM](https://user-images.githubusercontent.com/29613775/81621354-e3203c80-93f6-11ea-94d2-59d5aa8b3896.png)

When you press the Edit icon (pencil) the name should be highlighted in place and ready to be entered text from keyboard. Pencil icon should switch to a Check icon like in this updated screen:
https://projects.invisionapp.com/d/main#/console/17132809/400414454/preview

**Comment by JekaPolihovic** [comment]
@bagrinsergiu Тут не получиться сделать как просит Bogdan мы используем editable от antd https://ant.design/components/typography/#components-typography-demo-interactive , а у них нельзя поменять как он просит на значок проверки и просто чтобы выделился текст , ant добовляет сразу после нажатия input и значок , которые потом нельзя редактировать 

Тут либо надо новый ebitable делать , свой кастомный , либо подумать !

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - nu se poate de facut bg albastru in regimul de edit 

In ant este un exemplu cu componentul asta: https://ant.design/components/typography/#components-typography-demo-interactive

---

https://jmp.sh/MFFZqMB

**Comment by BogdanGCondurache** [comment]
@bagrinsergiu @JekaPolihovic can we at least stylise it like this?
https://projects.invisionapp.com/d/main?origin=v7#/console/17132809/400414454/preview

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic https://jmp.sh/6D8z04l
the styling is OK, but in Ant the text is kept in the field, not removed like in our case. When you want to edit a title, it's best to keep the existing text inside the field. Just make it (if possible) like [in Ant](https://ant.design/components/typography/#components-typography-demo-interactive).

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache 
1. OK
2. This functionality will be done when the functionality in the Table works, I just added this field
