### ISSUE TITLE
Search items in Menus sidebar

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#172]
https://jmp.sh/LogsOCU - we should add a search field under the select.
The search should be exactly like the one in here: https://jmp.sh/LogsOCU only the palceholder text should say "Search Items"

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - trebuei de ada`ugat in invisin

**Comment by BogdanGCondurache** [comment]
Done: this is the prototype in Invision:
https://projects.invisionapp.com/d/main#/console/17132809/400088324/preview
