### ISSUE TITLE
Comments desciption

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#173]
https://jmp.sh/JliKPFU
let's try to make it display on a single line. If not, we will change the text to be shorter.

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - daca atit e sidebar el nu incape acolo

**Comment by BogdanGCondurache** [comment]
OK, atunci sa punem textul:
"Comment enabled. Manage them here"
