### ISSUE TITLE
Comments sidebar area issues

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#176]
https://jmp.sh/tJNlvxG
When hovering Comments title the cursor needs to be a hand cursor. Same for the link "here".

Also, the functionality here when you click Comments should be the same as when you click the Published title above. A dropdown select opens with 2 options: 
Comments ON (green circle: #47CC24)
Comments OFF (red circle #CC2424)

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic 
https://jmp.sh/mXzk8z5
Comments lights are wrong. THe Red should be for OFF and green for ON

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache Need to remove this dropdiwn https://prnt.sc/sfzlit ?

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic this [dropdown](https://jumpshare.com/v/c7E5o9wlprL8GqoXpfng) will only appear when clicking on Comments title. Not on the word 'here'.

Clicking the word 'here' will go to a different tab, the one named Comments in the top bar: https://jmp.sh/hTiABzV
