### ISSUE TITLE
Categories Sidebar Area issues

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#177]
This was not implemented: https://jmp.sh/KhUI2n5

The design for this functionality already exists in the proto:
https://projects.invisionapp.com/d/main#/console/17132809/400328636/preview

same should happen for the Tags when clicking the plus icon.

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - asta urmeaza sa vedem daca asa o sa lucreze.

**Comment by JekaPolihovic** [comment]
https://github.com/bagrinsergiu/brizy-ui/issues/189

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - vad ca sa adaugat eu ma gindeam ca sa o vedem mai tiriziu daca e nevoie sau nu de optiunea asta
