### ISSUE TITLE
Leads Date font letter spacing

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#178]
https://jmp.sh/nzFEIrx
The letter spacing seems incorrect. 

It should be exactly like the texts in Categories column for example: https://jmp.sh/MaKujoD

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache Here the problem is not with Letter Spacing, there is a problem with the font, I downloaded Proxima Nova on the Internet, and in it all the dates are
Need to find a good font Proxima Nova!
https://prnt.sc/sf99m3 , https://prnt.sc/sf99z8

**Comment by BogdanGCondurache** [comment]
Here is the archive with the fonts:
[Prox-nova.zip](https://github.com/bagrinsergiu/brizy-ui/files/4615023/Prox-nova.zip)
