### ISSUE TITLE
Inputs that are clicked

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#185]
https://jmp.sh/vOv8A8W
Inputs when clicked should hide the placeholder

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache Here, when a click is clicked, the placeholder must be missing, it usually disappears when you write something, or is it specifically for this input is needed?

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - eu crerd ca e corect cum e acum. Placeholder dispare cind incepi sa scrii

**Comment by BogdanGCondurache** [comment]
@bagrinsergiu e bine da, am gresit eu cand am testat
