### ISSUE TITLE
Dropdown select sidebar

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#186]
https://jmp.sh/eRrpxta
these selects should look like these: https://jmp.sh/SwpocQP (same font size, same line height, etc). 

[These too](https://jmp.sh/5iY0Q2x) are not correct.

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - nu inteleg ce trebuei de fa`cut aici

**Comment by BogdanGCondurache** [comment]
THe link to second screenshot was wrong. THis is the corect one: https://jmp.sh/SwpocQP
