### ISSUE TITLE
Can you add perhaps so that I can download this icon?

### ISSUE THREAD

**Issue by JekaPolihovic** [bagrinsergiu/brizy-ui#192]
Can you add perhaps so that I can download this icon?
https://prnt.sc/sf8fh6

https://projects.invisionapp.com/d/main?origin=v7#/console/17132809/401393646/inspect?scrollOffset=800

**Comment by BogdanGCondurache** [comment]
Here is the icon SVG: 

[Edit Icon 12x12.svg.zip](https://github.com/bagrinsergiu/brizy-ui/files/4614883/Edit.Icon.12x12.svg.zip)

**Comment by JekaPolihovic** [comment]
Thanks
