### ISSUE TITLE
Content Bottom Button

### ISSUE THREAD

**Issue by bagrinsergiu** [bagrinsergiu/brizy-ui#20]
- [x] https://jmp.sh/mzKXqnC

**Comment by JekaPolihovic** [comment]
All ok 
https://prnt.sc/rzbc25

**Comment by bagrinsergiu** [comment]
close issue in this case

**Comment by bagrinsergiu** [comment]
- [ ]  ad this section on the bottom similar to search section 

https://jumpshare.com/v/8bHsxFDrVIws3YCmnxYa
