### ISSUE TITLE
Description not entered

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#201]
https://jmp.sh/LcnQirQ

Putem simula cum va arata interfata daca nu se vor introduce descriptions? Spatiul respectiv va fi scos automat sau va ramane containerul gol si va ocupa spatiul? Intreb pentru ca vom avea probleme pe partea de vizual daca spatiul ramane.

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - cred ca o sa fie eliminat spatiu
