### ISSUE TITLE
Search Fields line

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#228]
https://jmp.sh/TrKmelY
the Search fileds underline is not streching to the right side enough.

Also, are the left and right paddings the same for the icons below?

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - acolo este si scroll trebuei de calculatu cu el

**Comment by BogdanGCondurache** [comment]
@bagrinsergiu OK, ai dreptate. ramane asa.
