### ISSUE TITLE
Calendar dark

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#231]
https://jmp.sh/coSi2zN

I've made a mistake using the dark calendar in the design, let's chaneg it to the light version that can be found in Ant Design kit [here](https://jmp.sh/oMWSv3H).

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic the animation for opening the calendar is not correct. Should be exactly as the dropdown list in menus: https://jmp.sh/tdWbnFq (the opening animation, not the actual design)

**Comment by JekaPolihovic** [comment]
Done
