### ISSUE TITLE
Product Pricing Area

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#239]
https://jmp.sh/JGvlEOo

Product pricing area: 
https://projects.invisionapp.com/d/main#/console/17132809/417838973/preview

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic 
1. Regular Price field is somehow linked to SKU field. When entering a price it enters the same value in the SKU field too: https://jmp.sh/HTdSzEf

2. Regular Price & Sale Price fields should display the decimals after entering a number, like with Shopify: https://jmp.sh/oruyRxe

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache 
1. Done

2. Decimals can only be added to InputNumber https://ant.design/components/input-number/#components-input-number-demo-digit, but suffix (USD) https://prnt.sc/skf0i8 cannot be added,
This is how you can’t add https://prnt.sc/skf0i8, so this is empty but there are switches https://prnt.sc/skf1ho
