### ISSUE TITLE
Inventory & SKU

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#240]
https://jmp.sh/SV1KgPc

Inventory & Stock
https://projects.invisionapp.com/d/#/console/17132809/417838973/preview

The greyed out fields should be enabled only the Manage Stock switch in ON.

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache Give me please this icon svg https://prnt.sc/sk820m, i want to add this icon , I can not cut this icon

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic forfot to make it exportable, should be available now in this page:
https://projects.invisionapp.com/d/main#/console/17132809/418071250/inspect
