### ISSUE TITLE
Publish calendar (in future)

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#241]
https://jmp.sh/Jt3M8zv

When the underlined text with the publish date is clicked, a calendar with hours, mins & sec will be displayed. The component can be taken directly from Ant Design components.

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic if this is still in progress, please remove the Second column, we do not need that. Only days, hours and minutes. Thank you!

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache Delete this column https://prnt.sc/sj03c2 ?

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic yes, delete that column: https://prnt.sc/sj03c2

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache These headers were in the component in Ant or you drew them in the design, I just can’t find them https://prnt.sc/sj0rzj

**Comment by JekaPolihovic** [comment]
> @BogdanGCondurache These headers were in the component in Ant or you drew them in the design, I just can’t find them https://prnt.sc/sj0rzj

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic the headers are my own design, hopefuly you can add them in the component. If not, we can use it exactly like in Ant component.

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic 
1. The cursor needs to be Hand when hovering the date: https://jmp.sh/eeYLJ1j

2. The Hours and Minutes columns have a big space below the last value: https://jmp.sh/eeYLJ1j
This needs to be removed.

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache 

1. Done

2. Done

3. Done

4. Cannot be changed

5. Cannot be changed

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - pentru 5-6 trebuei alt issue acolo trebuei de schimbat in component

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic there is some weird movement when hovering the Hrs and Min columns: https://jmp.sh/IquvtbZ - not sure if it only happens on my end or not, but in the Ant component that is not visible.

@bagrinsergiu OK, pun issue separat.
