### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by bagrinsergiu** [bagrinsergiu/brizy-ui#256]
Promotion List

1/ Sylius: https://jmp.sh/XGxxLKZ
2/ Shopif: https://jmp.sh/XcnOOLS

Add new 

1/ Sylius: https://jmp.sh/ecXGR7L
2/ Shopify: https://jmp.sh/VLo9BK7

**Comment by BogdanGCondurache** [comment]
@bagrinsergiu astea sunt Coupons sau Discounts Codes, nu?

**Comment by bagrinsergiu** [comment]
@BogdanGCondurache - da
