### ISSUE TITLE
Trebuei sa incercam sa facem menu pe 2 nivele

### ISSUE THREAD

**Issue by bagrinsergiu** [bagrinsergiu/brizy-ui#257]
Sunt citeva componente unde o sa fie nevoei menu pe 2 nivele

1/ Produts
2/ Orders
3/ Blog
4/ ...

https://jumpshare.com/v/aoD9PqYSBIuRay5OBVJo

**Comment by BogdanGCondurache** [comment]
Sidebar Level 2 (Products):
https://projects.invisionapp.com/d/main#/console/17132809/418421559/preview

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic looks good, but we need more padding on the bottom, below the last item. https://jmp.sh/esVg9OU
Please make it the same padding size as above All Products
