### ISSUE TITLE
API fields and design

### ISSUE THREAD

**Issue by GunkaArtur** [bagrinsergiu/brizy-ui#267]
API fields:
### Product: 
There are no such fields in Products API
- [ ] What is this? https://jmp.sh/qBoDyTw
- [ ] No price in API https://jmp.sh/Ybhvj5K

### Product details:
There are no such fields in Products API
- [ ] country of origin https://jmp.sh/9KXW0Yz
- [ ] ISBN code https://jmp.sh/pU0mwrz
- [ ] description https://jmp.sh/PcnoYBn
- [ ] Sale price https://jmp.sh/Zh2SKbo
- [ ] Notify when stock reachs https://jmp.sh/LcNxY4A

**Comment by bagrinsergiu** [comment]
This issue was added to: https://github.com/bagrinsergiu/brizy-cms-ui/issues/19
