### ISSUE TITLE
Sorting on column titles

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#271]
https://jmp.sh/JEiWnlV

The sorting needs to be done only one the title and the arrows area, not outside. This are the hotspot areas, not more than that: https://jmp.sh/JEiWnlV

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache You can’t just take it and make it so that when you click on title there is sorting, in ant such functionality that only when you click on the whole row sort.

https://prnt.sc/slpz9x
https://ant.design/components/table/#components-table-demo-multiple-sorter

**Comment by BogdanGCondurache** [comment]
@bagrinsergiu OK, daca nu se poate face, asta e, o lasam asa. Cred ca se poate inchide issue, nu are sens sa mai stea aici.
