### ISSUE TITLE
Product Titles available space

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#272]
The horizontal space for each title is too narrow: https://jmp.sh/gsx8Hn0
We need to let the titles flow further to the right. The bounding box for the titles should extend until the x value (see the screenshot, basically same padding as on the right side of the Publish Indicator)

P.S: I've updated the [prototype page](https://projects.invisionapp.com/d/main#/console/17132809/417800305/preview) to show this better.

**Comment by JekaPolihovic** [comment]
https://prnt.sc/slojn3
