### ISSUE TITLE
Orders > Details

### ISSUE THREAD

**Issue by BogdanGCondurache** [bagrinsergiu/brizy-ui#278]
https://projects.invisionapp.com/d/main#/console/17132809/418784625/preview

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache Add Exportable This icons https://prnt.sc/sltbmq

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic they were made exportable from the start, not sure why it doesn't show on your end. Here it is on my screen: https://jmp.sh/mnz0fzS

In any case, here are the 3 icons exported as SVG
[icons-orders-total.zip](https://github.com/bagrinsergiu/brizy-ui/files/4676516/icons-orders-total.zip)

**Comment by JekaPolihovic** [comment]
@BogdanGCondurache but this icon https://prnt.sc/snbet3 ?

**Comment by BogdanGCondurache** [comment]
@JekaPolihovic here is the Refund icon: 
[Refund.svg.zip](https://github.com/bagrinsergiu/brizy-ui/files/4676690/Refund.svg.zip)
