### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by bagrinsergiu** [bagrinsergiu/brizy-ui#285]
Date time sa facut pe alb cu color picker cum a ramas?

Eu nu am putut gasi color picker si date time in invision. :: https://jumpshare.com/v/9M2Xmzzxm0Fn5S58OEy3

---

Daca punem pe alt putem sa punem color pickerul asta? 

https://casesandberg.github.io/react-color/

Asta e cel mai popular color picker pentru react si merge bine comparativ cu cel ce il avem noi in editor

**Comment by bagrinsergiu** [comment]
Referinta: https://github.com/bagrinsergiu/brizy-ui/issues/153

**Comment by BogdanGCondurache** [comment]
@bagrinsergiu da, date time si color picker vor fi albe. 

1. Date calendar va fi exact componentul din Ant, nu am mai desenat nimic acolo pt ca nu avea sens. Cel implementat acolo e bun (https://jmp.sh/AwPwHg3)

2. Color Picker se poate folosi oricare dintre astea doua: https://jmp.sh/mnz0fzS - daca ne trebuie si valorile pt R G B atunci cel de sus (Sketch). Daca putem merge si pe ceva simplificat, atunci al doilea (Block)
