### ISSUE TITLE
Broken Layout styles

### ISSUE THREAD

**Issue by oleg-brizy** [bagrinsergiu/brizy-ui#42]
In [CMS-UI](https://github.com/bagrinsergiu/brizy-cms-ui) the layout is divided in [three parts](https://github.com/bagrinsergiu/brizy-cms-ui/blob/c0f5337d9322b4458e41ceadf5cb70924052d332/src/layouts/Main/index.tsx#L9-L15): menu, header, content.

With `@import "~antd/dist/antd.css";` it looks ok

![StaticShot_15-04-2020_18-53-51](https://user-images.githubusercontent.com/59368968/79359119-d66d0d80-7f4a-11ea-9401-3c15f82a9ff1.png)

With [master version](https://github.com/bagrinsergiu/brizy-ui/tree/aba83727d182ad2e9f2fc0e95701813a23c85467) `@import "~@brizy/ui/dist/styles.css";` it looks broken - content goes under menu

![StaticShot_15-04-2020_19-00-10](https://user-images.githubusercontent.com/59368968/79359505-601cdb00-7f4b-11ea-971a-8c2c2947ebb0.png)

**Comment by JekaPolihovic** [comment]
@oleg-brizy 
Там должен идти sidebar (Sider) и в нем menu 
У меня такая структура сейчас в test-brizy-ui
![image](https://user-images.githubusercontent.com/15094004/79360346-75463980-7f4c-11ea-8ef5-32faf6ecf6d6.png)

**Comment by oleg-brizy** [comment]
Nope. The same problem on dev.

Why is this affected? Shouldn't you only customize colors and spaces (padding, margin)?

**Comment by JekaPolihovic** [comment]
@oleg-brizy 
Ну я делаю только стили , для компонетов , и тестирую их использую эти компоненты , в test-brizy-ui ( https://github.com/bagrinsergiu/test-brizy-ui )
Видно какие компоненты стилизованы 

Как ещё тестировать если не использовать их 

вот эти компонеты я использовал 

import {Layout, Menu, Form, Button, Typography, Input, Row, Col, Badge, Tag, Divider, Tabs, UploadBrizy, SpacerBrizy, Dropdown, Checkbox, Tooltip, Table, MultipleUploadBrizy, Card} from "@brizy/ui"

**Comment by JekaPolihovic** [comment]
@oleg-brizy 
Может мы должны договорится какие компоненты будем использовать ?
Просто мне Georgi сказал стилизовать компоненты те которые будем использовать

**Comment by oleg-brizy** [comment]
The problem comes from here

https://github.com/bagrinsergiu/brizy-ui/blob/ec3a2e0e2a62147edb990636a20b7e213127a14e/less/brizy-layout.less#L10-L12

https://github.com/bagrinsergiu/brizy-ui/blob/ec3a2e0e2a62147edb990636a20b7e213127a14e/less/brizy-sidebar.less#L3-L9

Why did you add these hardcoded sizes? This library is intended to be used in different layout combinations, not only one example drawn by our designer.

**Comment by JekaPolihovic** [comment]
@oleg-brizy 
Так это не Хардкод, переменых для того чтобы стилизовать это небыло и поэтому я создал файл для того или иного компонента 

Его также можно использовать в разных местах

**Comment by JekaPolihovic** [comment]
@oleg-brizy 
Как мне George обьяснил если нету возможности стилизовать какойто компонент то добавить для него файл и там стили прописывать.

**Comment by JekaPolihovic** [comment]
Там же из стилей для всех компонентов не только цвета менять нужно чтобы было как в дизайне в invision
А еше ширина , высота , отступы и тд 

А тут нету почти большей части 
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less

**Comment by oleg-brizy** [comment]
In antd all css classes are global. You customized your component for a specific example (example from invison) but the changes affected all usages of that component and now my basic layout is broken.

Settings `position: fixed` is a huge change in my point of view.

If existing component doesn't behave as required by design, better create a new component with new classes but don't change completely existing components behavior.

I am using `@brizy/ui` by copying examples from [`antd` docs](https://ant.design/components/layout/), so I am expecting it to behave exactly like antd (like examples in docs). If I want some custom Brizy behavior, I will use a custom brizy component.

**Comment by oleg-brizy** [comment]
Also for custom components, the styles should be in the same directory as component (not in a completely different directory) [as in antd](https://github.com/ant-design/ant-design/tree/master/components/layout) (see `style/`)

**Comment by JekaPolihovic** [comment]
Ну тут по дизайну все компоненты по другому идут и выглядят , получаеться что их всех надо как отделный компонет brizy делать , функционал antd же сохранился , и как ведут себя компоненты в antd , так и осталось 
https://www.loom.com/share/9137961649634218b74cd68e0f926b06

Я не совем понимаю что не так

**Comment by oleg-brizy** [comment]
You made the components to look exactly how it is required by invision screens and altered their sizes (in some cases radically with position:fixed).

This `@brizy/ui` library should be as a lego, like antd is, to be able to combine the components/layouts however you want, not only as in invision example.

I have the simplest example, [a basic layout](https://github.com/bagrinsergiu/brizy-ui/issues/42#issue-600408793), that was working fine. Now after I updated latest brizy/ui it is broken - the content for some reason goes under menu and has a big padding, all kind of hardcoded sizes, that  completely irrelevant for what I need/expect. I need the components to behave like antd examples, only with brizy colors (and maybe adjusted padding/margin).

What we have now in invision is just the beginning - only one example what we can build with brizy/ui. Later brizy/ui will be used by other developers to create plugins for Brizy editor and we will tell them "Hey, we have a UI library based on antd, so you can use antd code examples and our custom components", and they will try to use antd code examples and it will look completely different/unexpected.

I think with other components we will not have issues because they are independent blocs (unless you add position:absolute/fixed or negative margins).
The only big issue now is are layout components - they are affecting each other's position and can be combined in a lot of ways. For some reason one layout component now has position:fixed and it "flies away" from other components and destroys the logic of how that component can be used (it was customized only for an exact/specific example - an invision screen).

Please fix that hardcode sizes from layout components. I want layout components to behave as in antd docs (without weird position:fixed).

Again, I think all customizations should be fine as they are now, just don't alter layout components behavior/position/sizes (create a custom component if it's not possible to use the standard one).

----

At the moment I will revert to previous (initial) version of [`@brizy/ui` 0.0.2](https://www.npmjs.com/package/@brizy/ui) and try again `dev` branch after the customizations will be fixed.

**Comment by JekaPolihovic** [comment]
@oleg-brizy 
#43
Я убрал стороние стили , только как теперь оно будет выглядеть чтобы было как в дизайне 
Мне создать отдельно Sider, Header, Footer, Content для brizy?

**Comment by oleg-brizy** [comment]
Yes.
