### ISSUE TITLE
Menu tab must be blank ( it is not needed right now ) We plan to add content here later

### ISSUE THREAD

**Issue by bagrinsergiu** [bagrinsergiu/brizy-ui#59]
https://jmp.sh/74CiWHR

**Comment by bagrinsergiu** [comment]
Menu tab must be blank ( it is needed to delete or comment all html from This tab )

**Comment by JekaPolihovic** [comment]
@bagrinsergiu 
https://github.com/bagrinsergiu/test-brizy-ui/pull/15
