### ISSUE TITLE
Configure ant style to brizy ui

### ISSUE THREAD

**Issue by GheorgheP** [bagrinsergiu/brizy-ui#6]
Need to configure ant style to match brizy ui styles.

Ant reference about how to configure styles: https://ant.design/docs/react/customize-theme

Brizy UI reference: https://projects.invisionapp.com/d/main#/projects/prototypes/17132809
Refer only **CMS + ACF** section.

**Comment by bagrinsergiu** [comment]
O sa facem isusues mai mici
