### ISSUE TITLE
Select is not working properly

### ISSUE THREAD

**Issue by bagrinsergiu** [bagrinsergiu/brizy-ui#60]
https://jmp.sh/jjzoEEX

**Comment by JekaPolihovic** [comment]
https://www.loom.com/share/83369fbbf0b74affb53d42e65ccc4d11

**Comment by JekaPolihovic** [comment]
I think this problem to js, Does not track position.

**Comment by GheorgheP** [comment]
@JekaPolihovic, the video quality is pretty low, but I think the element gets position `fixed` for some reasons, instead of `absolute`, so thi may be a quick fix.

**Comment by JekaPolihovic** [comment]
@GheorgheP , Нет там стоит `position absolute`, просто по какой то причине позиция не отслеживаеться , но если делаешь шире страницу как в видео я сделал, то `dropdown` становиться на место.

**Comment by GheorgheP** [comment]
> @GheorgheP , Нет там стоит `position absolute`, просто по какой то причине позиция не отслеживаеться , но если делаешь шире страницу как в видео я сделал, то `dropdown` становиться на место.

@JekaPolihovic, because dropdown position on resize. This will not help you to fix the problem.
