### ISSUE TITLE
this line seems 2px must be 1 px

### ISSUE THREAD

**Issue by bagrinsergiu** [bagrinsergiu/brizy-ui#64]
https://jmp.sh/OBR1e6j

**Comment by JekaPolihovic** [comment]
Строка имеет 1px 
Проверил линейкой 
https://prnt.sc/s36kgj

**Comment by bagrinsergiu** [comment]
u menia tot transfost 1px border delaier v 2px 

ia ne znaiu pocemu tac

**Comment by JekaPolihovic** [comment]
@bagrinsergiu ,
Переделал по другому эту линию и убрал transform, может так измениться что то.
